### PR TITLE
Use WixPSExtension to install PowerShell extension

### PR DESCRIPTION
**Pull request by mbiebl**
Instead of using a managed custom action and InstallUtil.exe, we vastly
simplify the installation using WixPSExtension.

Fixes: #33

### CODE REVIEW

**Comment by mbiebl** [comment]
There is some whitespace mix-up, so #43 should probably be merged first.

**Comment by lextm** [comment]
For a legacy project, I really try to avoid huge pull requests like #43 which introduces nothing but source code format changes.

If possible, undo unnecessary line changes in this pull request.

**Comment by mbiebl** [comment]
> If possible, undo unnecessary line changes in this pull request.

Those are done automatically by Visual Studio. I can undo them manually, but this is kinda annoying having to do that every time I touch the file.
If you don't want to merge #43, would you be ok, if I commits contain white space files for files that are touched by a PR?

**Comment by mbiebl** [comment]
Anyway, will redo this commit to drop unnecessary white space changes. Feel free to close #43 

If you'd prefer the Modules based approach over fixing the Snapin one, please let me know

**Comment by mbiebl** [comment]
Force-Pushed with unnecessary white space changes removed.

Please have another look

**Review by lextm — APPROVED** [review]

**Pull request merged**
