### PR TITLE
Use DTF instead of InstallUtil to call our custom actions

### LINKED ISSUE #28: upgrade routine broken
Hi,

I've just upgraded from v2.1 to v2.2. 
After the upgrade, PHPManager was no longer shown in IIS Manager.
I had to uninstall and then reinstall PHPManager. After that it was functional again and available in IIS Manager.

### PR DESCRIPTION
**Pull request by mbiebl**
As we no longer need to care for older Windows installations (see #45),
switch back to using DTF to call our custom actions.

For a couple of good reasons why DTF is a good idea, see
http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org/2021-March/009681.html

This also fixes the upgrade routine.

Fixes: #28

### CODE REVIEW

**Comment by mbiebl** [comment]
Hi, any updates?

**Comment by lextm** [comment]
Limited resources to finish testing it on all supported platforms. Probably some time in the summer.

**Comment by mbiebl** [comment]
Okay. If there is anything I can help you with, please let me know.

**Comment by jrose323** [comment]
Any update on getting this merged? It would solve two open issues on the board currently. I had the same issue with 2.7 install where the icon disappeared in IIS. Running a repair on the installation resolved the issue.

**Comment by lextm** [comment]
Done in #57 by reverting to a very old version.

**Pull request closed without merging**
